### ISSUE TITLE
"segmentation fault" when I do reading file and detecting at same time 

### ISSUE THREAD

**Issue by alacic** [wzhvictor/libinjection-python#2]
When I do reading file and detecting at same time, "segmentation fault" occurred. 

## env

1. ubuntu 18.04
2. python 3.7.3
3. 270000+ lines queries

## code

```python
from libinjection import is_xss
from libinjection import is_sql_injection as is_sqli

if __name__ == "__main__":
    query_file = "./querys.txt"
    sqlis = []
    xss = []
    with open(query_file) as f:
        # qs = f.readlines()
        for line in f:
            if is_sqli(line):
                sqlis.append(line)
            elif is_xss(line):
                xss.append(line)

    print(f"{len(sqlis)}")
```

**Comment by wzhvictor** [comment]
SQL injection detection or xss？

**Comment by alacic** [comment]
SQL injection detection

**Comment by wzhvictor** [comment]
I have not found the problem about many testing cases. I guess it is the Python version's problem. Can you send your cases to my email? wzhvictor@outlook.com

**Comment by alacic** [comment]
1. I send you my cases by qq mail.
2. when I change code "sqlis.append(line)" to "pass",  no error occurred.

```python
with open(query_file) as f:
        for line in f:
            if is_sqli(line):
                pass
                # sqlis.append(line)
```

**Comment by wzhvictor** [comment]
I just tried it. No crash...
My Device：MacOS, Python 3.9.0

You try to use other platform...

**Comment by alacic** [comment]
thx.

1. I tried libinjection-python on macos just now, it works well.
2. I tried python 3.9.6 on linux, also works well.
3. I tried the c/c++ code, also works well.

It seems to be problem with platform or python version.
