### ISSUE TITLE
Add pypi token to upload wheels as part of build process

### ISSUE THREAD

**Issue by john-g-g** [wzhvictor/libinjection-python#8]
For the github action to work and upload the wheels to pypi, there needs to be a github secret named `PYPI_API_TOKEN` set with the value of a new or existing pypi token, and the git commit should be tagged as `v1.1.6`. 

To set the secret: go to Settings > Secrets.

To tag the current master branch release:
`git checkout master && git pull & git tag v1.1.6 && git push origin v1.1.6`

**Comment by john-g-g** [comment]
Any luck?

**Comment by wzhvictor** [comment]
Thanks, I spent some time testing and setting Actions, you can try.
